### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by purvishce** [itgroove-studios/SPF-Classic-Port-Example#1]
I have SP2019. Try to use this solution in my environment. It works for Modern site but it doesn't work. Am I missing? When and How ClassicVersion.ts gets called?

**Comment by lworkman** [comment]
@purvishce are you using SharePoint on-premise? This project has only been tested for SharePoint online, so I can't speak as to whether it works on-prem.

The matching blob post may also help you: https://itgroove.net/studios/using-a-sharepoint-framework-extension-with-classic-sharepoint/

To answer your question: `ClassicVersion.ts` gets compiled by the gulp task `build-classic` and outputs a folder containing a script and style file.

**Comment by purvishce** [comment]
Thanks for your response. It works on SP2019 - On premise Classic and Modern pages but it creates .d.ts files next to ts file. 

Is there any way I can changes the pah of it?

-Purvish

**Comment by lworkman** [comment]
The project uses webpack, so you just need to alter the `webpack.config.js` file to change paths:

https://github.com/itgroove-studios/SPF-Classic-Port-Example/blob/master/webpack.config.js

**Comment by purvishce** [comment]
Thanks for your reply. This is great solution. Thanks for sharing it. It's big help to us.
